### ISSUE TITLE
Issue With Nginx Unit

### ISSUE THREAD

**Issue by mjBayati** [uriyyo/fastapi-lifespan-manager#107]
Hi,
Thanks for your useful utility to support multi lifespans.
I have issue running application with `nginx-unit` when using your library.
the error is: 
```

 File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 680, in lifespan
    raise RuntimeError(
RuntimeError: The server does not support "state" in the lifespan scope.


```

do you have any idea how to fix this?

**Comment by uriyyo** [comment]
Hi @mjBayati,

I released a small fix that should possibly fix your issue.

Could you please try to use `0.1.2` version?

**Comment by mjBayati** [comment]
Hello again,
thanks for your supports,
still throws error on startup 

```

File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 680, in lifespan
    raise RuntimeError(
RuntimeError: The server does not support "state" in the lifespan scope.


```

**Comment by mjBayati** [comment]
I upgraded lifespan-manager to it's latest version also

**Comment by uriyyo** [comment]
Could you please also verify that you are using the latest version of `nginx-unit`?

ASGI State support was added in version `1.31.0` .

Please see issue https://github.com/nginx/unit/issues/864 and changelog https://github.com/nginx/unit/blob/master/CHANGES

**Comment by mjBayati** [comment]
thanks @uriyyo ,
issue was about nginx unit
I switched to uvicorn's base deployment.
and issue is resolved now.

**Comment by uriyyo** [comment]
Great, then I guess I can close this issue.
